// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP5rQOIpBK68_zzLnpU6IJBzzvlSIcKH0',
    appId: '1:258636981076:web:cafaedf68ba5bf086fdec1',
    messagingSenderId: '258636981076',
    projectId: 'almahub-1fc5a',
    authDomain: 'almahub-1fc5a.firebaseapp.com',
    storageBucket: 'almahub-1fc5a.firebasestorage.app',
    measurementId: 'G-ZBTJFFFC8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsmXrzBoptTUXe9FkMDY_14T5Lb3bkUKg',
    appId: '1:258636981076:android:89ab31207a650a3e6fdec1',
    messagingSenderId: '258636981076',
    projectId: 'almahub-1fc5a',
    storageBucket: 'almahub-1fc5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsPDNOQ2cqaQKSDAvirCy-Vzcl0v-4VP0',
    appId: '1:258636981076:ios:8563ade2dd2537106fdec1',
    messagingSenderId: '258636981076',
    projectId: 'almahub-1fc5a',
    storageBucket: 'almahub-1fc5a.firebasestorage.app',
    iosBundleId: 'com.example.almahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsPDNOQ2cqaQKSDAvirCy-Vzcl0v-4VP0',
    appId: '1:258636981076:ios:8563ade2dd2537106fdec1',
    messagingSenderId: '258636981076',
    projectId: 'almahub-1fc5a',
    storageBucket: 'almahub-1fc5a.firebasestorage.app',
    iosBundleId: 'com.example.almahub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP5rQOIpBK68_zzLnpU6IJBzzvlSIcKH0',
    appId: '1:258636981076:web:5ce1936c5ef39a6b6fdec1',
    messagingSenderId: '258636981076',
    projectId: 'almahub-1fc5a',
    authDomain: 'almahub-1fc5a.firebaseapp.com',
    storageBucket: 'almahub-1fc5a.firebasestorage.app',
    measurementId: 'G-90QSHBQK0Q',
  );
}
